[plugins]
android-application = "com.android.application:9.0.0-rc01"
android-kotlin-multiplatform-library = "com.android.kotlin.multiplatform.library:9.0.0-rc01"
android-library = "com.android.library:9.0.0-rc01"
